apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-phl
spec:
  acme:
    email: imamariefrahmann@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-phl
    solvers:
    - http01:
        ingress:
          class: alb
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-phl
spec:
  selfSigned: {}