replicas: 1
# This is hardened configuration for the metrics-server Helm chart
# Ref: https://github.com/kubernetes-sigs/metrics-server/tree/master/charts/metrics-server
# https://github.com/kubernetes-sigs/metrics-server/blob/master/charts/metrics-server/ci/tls-certManager-values.yaml
args:
  - --kubelet-insecure-tls

apiService:
  insecureSkipTLSVerify: false
# Required cert-manager installed
tls:
  type: "cert-manager"


  clusterDomain: cluster.local

  certManager:
    addInjectorAnnotations: true
    existingIssuer:
      enabled: true
      kind: "ClusterIssuer"
      name: "selfsigned-phl"
    # Set the requested duration (i.e. lifetime) of the Certificate.
    # See https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec
    duration: 1h
    # How long before the currently issued certificate’s expiry cert-manager should renew the certificate.
    # See https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec
    renewBefore: 30m