mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.66.0"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  annotations:
    iam.gke.io/gcp-service-account: phl-mstr-addon-otel-collector@phl-platform.iam.gserviceaccount.com
  name: phl-mstr-addon-otel-collector

alternateConfig:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

  exporters:
    googlecloud:
      project: phl-platform
      trace:
        use_insecure: false

  processors:
    batch: {}

  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133

  service:
    extensions:
      - health_check
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [googlecloud]

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    protocol: TCP
    appProtocol: grpc
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP

service:
  type: ClusterIP

podLabels:
  app: otel-collector
