# Prometheus values.yaml
server:
  ingress:
    enabled: true
    className: nginx
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "prometheus.lokal.blast.co.id"
      external-dns.alpha.kubernetes.io/ttl: "300"
      external-dns.alpha.kubernetes.io/target: "127.0.0.1"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-phl"
    hosts:
      - prometheus.lokal.blast.co.id
    path: /
    pathType: Prefix
    tls:
      - secretName: prometheus-server-tls
        hosts:
          - prometheus.lokal.blast.co.id
prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
    mountPropagation: HostToContainer