# Prometheus values.yaml
server:
  ingress:
    enabled: true
    className: nginx
    annotations:
      external-dns.alpha.kubernetes.io/hostname: prometheus.local.blast.co.id
      external-dns.alpha.kubernetes.io/ttl: "300"
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-phl"
    hosts:
      - prometheus.local.blast.co.id
    path: /
    pathType: Prefix
    tls:
      - secretName: prometheus-server-tls
        hosts:
          - prometheus.local.blast.co.id
prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
    mountPropagation: HostToContainer