apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.appSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
{{- range $key, $val := .Values.appSecret.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
type: Opaque