apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  commonName: metrics-server
  dnsNames:
  secretName: metrics-server
  usages:
    - server auth
    - client auth
  privateKey:
    algorithm: RSA
    size: 2048
  duration: lifetime
  renewBefore: 8760h
  issuerRef:
    name: metrics-server-issuer
    kind: Issuer
    group: cert-manager.io