controller:
  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 75
    targetMemoryUtilizationPercentage: 75
  ingressClassResource:
    enabled: true
    name: nginx
    default: false
    annotations:
      kubernetes.io/ingress.class: nginx
  ingressClass: nginx