apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name | replace "_" "-" }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.appSecret.annotations }}
  annotations:
    {{- toYaml .Values.appSecret.annotations | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  config.json: |-
    {{- range $key, $value := .Values.appSecret.secrets }}
    {{ $key }}='{{ $value }}'
    {{- end }}