receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  # googlecloud:
  #   project: fta-platform
  #   trace:
  #     use_insecure: false
  prometheus:
    endpoint: "0.0.0.0:9464"

processors:
  batch: {}

service:
  pipelines:
    # traces:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [googlecloud]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]